# AWS CodeBuild spec
version: 0.2
    
phases:   
  install:
    runtime-versions:
      dotnet: latest
      
  build:
    commands:
      - echo Build started on `date`
      - dotnet build **/*.sln
