# AWS CodeBuild spec
version: 0.2
    
phases:   
  install:
    runtime-versions:
      dotnet: latest
      
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore DataProcessor\DataProcessor.sln
      
  build:
    commands:
      - echo Build started on `date`
      - dotnet build DataProcessor\DataProcessor.sln
